image: "node:8"

before_script:
  - echo $NPMRC | base64 -d > ~/.npmrc
  - npm config set registry https://devops.wendys.com/nexus/repository/npm-all/

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - tags
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - es/
      - lib/

deploy:
  stage: deploy
  only:
    - tags
  script:
    - npm version $CI_COMMIT_TAG --allow-same-version --no-git-tag-version
    - npm publish  --registry https://devops.wendys.com/nexus/repository/npm-internal/
  dependencies:
    - build